// GAME
export const NEXT_TURN = "NEXT_TURN";
export const DEAL_CARD = "DEAL_CARD";

//PLAYERS
export const DRAW_CARD = "DRAW_CARD";
export const PLAY_CARD = "PLAY_CARD";
export const MAKE_CARD_ACTIVE = "MAKE_CARD_ACTIVE";

// THE  MATRIX
export const CLAIM_BOARD_SPACE = "CLAIM_BOARD_SPACE";

// FIREBASE CONNECTIVITY
export const GET_BOARD_STATE = "GET_BOARD_STATE";
export const PUT_BOARD_STATE = "PUT_BOARD_STATE";
